import { Category, Translation } from './types';
import { 
  LayoutDashboard, 
  List, 
  Settings as SettingsIcon, 
  PieChart, 
  Wallet, 
  ArrowUpCircle, 
  ArrowDownCircle, 
  Plus,
  Trash2,
  Save,
  Download,
  Upload,
  Printer,
  Moon,
  Sun,
  Globe,
  Sparkles,
  Search,
  Filter,
  Calendar,
  ChevronDown,
  LogOut,
  Pencil,
  Lock,
  Cloud,
  RefreshCw,
  CheckCircle,
  HardDrive,
  CloudUpload,
  CloudDownload
} from 'lucide-react';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Salary', type: 'income', color: '#10b981' },
  { id: 'c2', name: 'Freelance', type: 'income', color: '#34d399' },
  { id: 'c3', name: 'Food', type: 'expense', color: '#f87171' },
  { id: 'c4', name: 'Transport', type: 'expense', color: '#fbbf24' },
  { id: 'c5', name: 'Utilities', type: 'expense', color: '#60a5fa' },
  { id: 'c6', name: 'Entertainment', type: 'expense', color: '#a78bfa' },
];

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'MMK', symbol: 'Ks', name: 'Myanmar Kyat' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' }
];

export const TRANSLATIONS: Translation = {
  dashboard: { en: 'Dashboard', my: 'ဒက်ရှ်ဘုတ်' },
  transactions: { en: 'Transactions', my: 'ငွေစာရင်းများ' },
  settings: { en: 'Settings', my: 'ဆက်တင်များ' },
  totalIncome: { en: 'Total Income', my: 'စုစုပေါင်း ဝင်ငွေ' },
  totalExpense: { en: 'Total Expense', my: 'စုစုပေါင်း ထွက်ငွေ' },
  balance: { en: 'Balance', my: 'လက်ကျန်ငွေ' },
  addTransaction: { en: 'Add Transaction', my: 'စာရင်းအသစ်ထည့်ရန်' },
  save: { en: 'Save', my: 'သိမ်းဆည်းပါ' },
  cancel: { en: 'Cancel', my: 'မလုပ်တော့ပါ' },
  delete: { en: 'Delete', my: 'ဖျက်ပါ' },
  edit: { en: 'Edit', my: 'ပြင်ဆင်ပါ' },
  date: { en: 'Date', my: 'နေ့စွဲ' },
  amount: { en: 'Amount', my: 'ပမာဏ' },
  category: { en: 'Category', my: 'အမျိုးအစား' },
  note: { en: 'Note', my: 'မှတ်ချက်' },
  type: { en: 'Type', my: 'အမျိုးအစား' },
  income: { en: 'Income', my: 'ဝင်ငွေ' },
  expense: { en: 'Expense', my: 'ထွက်ငွေ' },
  search: { en: 'Search...', my: 'ရှာဖွေရန်...' },
  filterByDate: { en: 'Filter by Date', my: 'နေ့စွဲဖြင့် ရှာပါ' },
  allCategories: { en: 'All Categories', my: 'အမျိုးအစားအားလုံး' },
  appearance: { en: 'Appearance', my: 'အသွင်အပြင်' },
  darkMode: { en: 'Dark Mode', my: 'အမှောင်စနစ်' },
  language: { en: 'Language', my: 'ဘာသာစကား' },
  currency: { en: 'Currency', my: 'ငွေကြေး' },
  dataManagement: { en: 'Data Management', my: 'ဒေတာ စီမံခန့်ခွဲမှု' },
  backupData: { en: 'Backup to File', my: 'ဖိုင်အဖြစ် သိမ်းဆည်းရန်' },
  restoreData: { en: 'Restore from File', my: 'ဖိုင်မှ ပြန်ယူရန်' },
  printReport: { en: 'Print Report', my: 'စာရင်းထုတ်ရန်' },
  manageCategories: { en: 'Manage Categories', my: 'အမျိုးအစားများ စီမံရန်' },
  addCategory: { en: 'Add Category', my: 'အမျိုးအစားအသစ် ထည့်ရန်' },
  customCategories: { en: 'Custom Categories', my: 'စိတ်ကြိုက် အမျိုးအစားများ' },
  aiInsights: { en: 'AI Insights', my: 'AI အကြံပြုချက်' },
  aiAnalyze: { en: 'Analyze Finances', my: 'ငွေကြေး သုံးသပ်ရန်' },
  aiLoading: { en: 'Analyzing...', my: 'သုံးသပ်နေသည်...' },
  noTransactions: { en: 'No transactions found', my: 'စာရင်းများ မရှိပါ' },
  recentTransactions: { en: 'Recent Transactions', my: 'လတ်တလော စာရင်းများ' },
  today: { en: 'Today', my: 'ယနေ့' },
  timeFilter: { en: 'Period', my: 'အချိန်ကာလ' },
  day: { en: 'Day', my: 'နေ့' },
  week: { en: 'Week', my: 'အပတ်' },
  month: { en: 'Month', my: 'လ' },
  allTime: { en: 'All Time', my: 'အားလုံး' },
  dateRange: { en: 'Range', my: 'အပိုင်းအခြား' },
  startDate: { en: 'Start', my: 'စရက်' },
  endDate: { en: 'End', my: 'ဆုံးရက်' },
  totalFiltered: { en: 'Result Total', my: 'ရှာဖွေတွေ့ရှိငွေပမာဏ' },
  netBalance: { en: 'Net', my: 'လက်ကျန်' },
  logout: { en: 'Log Out', my: 'အကောင့်ထွက်ရန်' },
  username: { en: 'Username', my: 'အသုံးပြုသူအမည်' },
  password: { en: 'Password', my: 'စကားဝှက်' },
  login: { en: 'Login', my: 'အကောင့်ဝင်ရန်' },
  invalidCredentials: { en: 'Invalid username or password', my: 'အသုံးပြုသူအမည် (သို့) စကားဝှက် မှားယွင်းနေပါသည်' },
  welcomeBack: { en: 'Welcome Back', my: 'ကြိုဆိုပါတယ်' },
  enterPassword: { en: 'Enter Password', my: 'စကားဝှက်ရိုက်ထည့်ပါ' },
  confirm: { en: 'Confirm', my: 'အတည်ပြုပါ' },
  wrongPassword: { en: 'Incorrect Password', my: 'စကားဝှက်မှားယွင်းနေပါသည်' },
  editTransaction: { en: 'Edit Transaction', my: 'စာရင်းပြင်ဆင်ရန်' },
  deleteConfirm: { en: 'Delete Transaction?', my: 'စာရင်းဖျက်ရန် သေချာပါသလား' },
  deleteCategoryConfirm: { en: 'Delete this category?', my: 'ဤအမျိုးအစားကို ဖျက်မည်လား' },
  pickColor: { en: 'Color', my: 'အရောင်' },
  securityCheck: { en: 'Security Check', my: 'လုံခြုံရေး စစ်ဆေးခြင်း' },
  // Google Drive specific translations
  connectDrive: { en: 'Connect Google Drive', my: 'Google Drive ချိတ်ဆက်ပါ' },
  driveBackup: { en: 'Google Drive Backup', my: 'Google Drive တွင်သိမ်းရန်' },
  backupToDrive: { en: 'Backup to Drive', my: 'Drive သို့ သိမ်းဆည်းပါ' },
  restoreFromDrive: { en: 'Restore Last Backup', my: 'နောက်ဆုံးဖိုင် ပြန်ယူပါ' },
  driveConnected: { en: 'Connected to Drive', my: 'Drive ချိတ်ဆက်ပြီးပါပြီ' },
  backupSuccess: { en: 'Backup successful!', my: 'သိမ်းဆည်းခြင်း အောင်မြင်သည်' },
  restoreSuccess: { en: 'Restored successfully!', my: 'ပြန်လည်ရယူခြင်း အောင်မြင်သည်' },
  noBackupFound: { en: 'No backup found in Drive', my: 'Drive တွင် ဖိုင်မရှိပါ' },
  driveDesc: { en: 'Connect to Google Drive to backup your data safely to the cloud and restore it on any device.', my: 'သင့်ဒေတာများကို Cloud တွင် လုံခြုံစွာသိမ်းဆည်းရန်နှင့် အခြားစက်များတွင် ပြန်လည်ရယူရန် Google Drive ချိတ်ဆက်ပါ။' },
  syncData: { en: 'Sync Data', my: 'ဒေတာ ချိတ်ဆက်ရန်' },
  uploadToCloud: { en: 'Upload to Cloud', my: 'Cloud သို့ တင်ရန်' },
  downloadFromCloud: { en: 'Download from Cloud', my: 'Cloud မှ ရယူရန်' },
  syncDesc: { en: 'Transfer data between devices using Google Drive.', my: 'Google Drive အသုံးပြု၍ စက်များအကြား ဒေတာလွှဲပြောင်းပါ။' },
  step1: { en: 'Use this to save current data to cloud.', my: 'လက်ရှိဒေတာများကို Cloud တွင်သိမ်းရန် ဤအရာကိုသုံးပါ။' },
  step2: { en: 'Use this to load data from cloud to this device.', my: 'Cloud မှ ဒေတာများကို ဤစက်ထဲသို့ထည့်ရန် ဤအရာကိုသုံးပါ။' }
};

export const ICONS = {
  LayoutDashboard,
  List,
  SettingsIcon,
  PieChart,
  Wallet,
  ArrowUpCircle,
  ArrowDownCircle,
  Plus,
  Trash2,
  Save,
  Download,
  Upload,
  Printer,
  Moon,
  Sun,
  Globe,
  Sparkles,
  Search,
  Filter,
  Calendar,
  ChevronDown,
  LogOut,
  Pencil,
  Lock,
  Cloud,
  RefreshCw,
  CheckCircle,
  HardDrive,
  CloudUpload,
  CloudDownload
};